### ISSUE TITLE
Don't see progress bar

### ISSUE THREAD

**Issue by TheUadzhet** [KoljaWindeler/ytube_music_player#108] opened 2021-07-05 17:46 UTC
![Screen Shot 2021-07-05 at 20 46 02](https://user-images.githubusercontent.com/49291718/124505371-044da480-ddd2-11eb-85e1-cc193195c7da.png)

**Comment by KoljaWindeler** [comment] 2021-07-05 19:13
What Version are you running. Can you copy a screenshot of the state page of the player ... Developer tools -> state, search for the entity

**Comment by TheUadzhet** [comment] 2021-07-07 05:45
> What Version are you running. Can you copy a screenshot of the state page of the player ... Developer tools -> state, search for the entity

![Screen Shot 2021-07-07 at 08 42 31](https://user-images.githubusercontent.com/49291718/124706331-bafb7300-deff-11eb-8739-07c12ba7580a.png)

**Comment by KoljaWindeler** [comment] 2021-07-07 05:48
While playing please

**Comment by TheUadzhet** [comment] 2021-07-07 05:55
> While playing please

![Screen Shot 2021-07-07 at 08 53 51](https://user-images.githubusercontent.com/49291718/124707144-1843f400-df01-11eb-8cdb-207b480245f7.png)

**Comment by KoljaWindeler** [comment] 2021-07-07 06:45
Strange, there is no media_duration attribute. Are you running the latest version? Is this the same for all tracks?

**Comment by TheUadzhet** [comment] 2021-07-07 06:52
> Strange, there is no media_duration attribute. Are you running the latest version? Is this the same for all tracks?

As I know, yep, I use the latest version downloaded just yesterday via HACS. Same for all tracks.

**Comment by KoljaWindeler** [comment] 2021-07-07 07:07
ah I know the cause .. your remote player (the device that actually does the playback) doesn't support the _media_duration attribute. Please check the attributes of the media_player.mpd ... that should also lag the media_duration. Those attributes are copied from the remote player to the ytube_music_player attributes ... strange that the MPD supports position but not duration though

**Comment by TheUadzhet** [comment] 2021-07-07 07:09
> ah I know the cause .. your remote player (the device that actually does the playback) doesn't support the _media_duration attribute. Please check the attributes of the media_player.mpd ... that should also lag the media_duration. Those attributes are copied from the remote player to the ytube_music_player attributes ... strange that the MPD supports position but not duration though

So, any ideas how to deal with it?

**Comment by KoljaWindeler** [comment] 2021-07-07 08:00
Buy a chromecast ;)

**Comment by TheUadzhet** [comment] 2021-07-07 08:16
> Buy a chromecast ;)
Google killed Chromecast audio with aux, sadly.
Thanks anyway, good integration :)

**Comment by KoljaWindeler** [comment] 2021-07-07 08:26
I guess another way to solve it would be to ask the guys of the mpd integration ... They might me able to add that attribute.
I guess we can close this here, right?

**Closed by KoljaWindeler** 2021-07-07 08:26 UTC

**Comment by KoljaWindeler** [comment] 2021-07-07 08:31
From https://github.com/svenvc/mpdclient

I can see that the status contains those fields:
(MPDClient new host: 'audio359') status.

 "a Dictionary(
   #audio->'44100:16:2'
   #bitrate->618
   #consume->0
   #elapsed->54.659
   #mixrampdb->0.0
   #nextsong->1
   #nextsongid->107
   #playlist->31
   #playlistlength->8
   #random->0
   #repeat->0
   #single->0
   #song->0
   #songid->106
   #state->'play'
   #time->'55:291'
   #volume->95 )"

elapsed is used as position. I'd guess that time could be the total_duration

**Comment by TheUadzhet** [comment] 2021-07-07 08:32
> I guess another way to solve it would be to ask the guys of the mpd integration ... They might me able to add that attribute.
> I guess we can close this here, right?

I have already asked they – https://github.com/Poeschl/Hassio-Addons/issues/257

**Comment by KoljaWindeler** [comment] 2021-07-07 08:44
You could try this: https://raw.githubusercontent.com/KoljaWindeler/core/dev/homeassistant/components/mpd/media_player.py
you have to replace your mpd/media_player.py file with the linked above. 
I'm unable to test it 
https://github.com/KoljaWindeler/core/commit/765a5e2a28ca274977f7e63ef73f84b67ae92691#diff-a7eafacb96b1c85db1f2b13fe416aebba50960c6010e82c3fe84c895ab39c0de

I'll submit a pull request once you can confirm that it works

**Comment by TheUadzhet** [comment] 2021-07-07 08:54
> You could try this: https://raw.githubusercontent.com/KoljaWindeler/core/dev/homeassistant/components/mpd/media_player.py
> you have to replace your mpd/media_player.py file with the linked above.
> I'm unable to test it
> [KoljaWindeler/core@765a5e2#diff-a7eafacb96b1c85db1f2b13fe416aebba50960c6010e82c3fe84c895ab39c0de](https://github.com/KoljaWindeler/core/commit/765a5e2a28ca274977f7e63ef73f84b67ae92691#diff-a7eafacb96b1c85db1f2b13fe416aebba50960c6010e82c3fe84c895ab39c0de)
> 
> I'll submit a pull request once you can confirm that it works

I use a Home Assistant OS, I guess it is not possible to have access to edit addons

**Comment by stboch** [comment] 2021-07-07 10:46
you can make these changes even on home-assistant is just copy mpd everything into a new folder in custom_componets and make the changes in that folder.

**Comment by KoljaWindeler** [comment] 2021-07-08 08:21
correct, did you try that @TheUadzhet ?

**Comment by TheUadzhet** [comment] 2021-07-08 13:40
> you can make these changes even on home-assistant is just copy mpd everything into a new folder in custom_componets and make the changes in that folder.

I've made a folder but nothing has happened 
![Screen Shot 2021-07-08 at 16 39 23](https://user-images.githubusercontent.com/49291718/124931683-2120ec80-e00b-11eb-84f6-57abc3868fa7.png)
