### ISSUE TITLE
ytube_music_player unable to play playlists

### ISSUE THREAD

**Issue by aguscaba** [KoljaWindeler/ytube_music_player#228] opened 2023-01-31 18:34 UTC
Hi, I'm recently facing issues while trying to play any playlist using the ytube_music_player integration which was working good, now I ran the example automation from the documentation page:

Only changed the "source" and the playlist id

```
alias: ytube morning routine
sequence:
  - service: media_player.select_source
    data:
      source: media_player.pantalla_google
      entity_id: media_player.ytube_music_player
  - service: media_player.shuffle_set
    data:
      shuffle: true
      entity_id: media_player.ytube_music_player
  - service: media_player.play_media
    data:
      entity_id: media_player.ytube_music_player
      media_content_id: RL36w98SNnACPF2PeSg6U6ZL0Vn3_Iu
      media_content_type: playlist
mode: single
```

Earlier it was running perfectly the only thing that change is that recently I got an update of the integration on my HACS

Here is the complete event log:

```
2023-01-31 18:21:59.479 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source(media_player.pantalla_google)
2023-01-31 18:21:59.480 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input media_player.pantalla_google/ current media_player.ninos)  [E]
2023-01-31 18:21:59.480 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.pantalla_google as player
2023-01-31 18:21:59.481 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source
2023-01-31 18:21:59.494 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] set_shuffle: True
2023-01-31 18:21:59.494 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] _tracks_to_attribute
2023-01-31 18:21:59.495 DEBUG (MainThread) [custom_components.ytube_music_player.sensor] updating ytube sensor
2023-01-31 18:21:59.495 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_extra_sensor [E]
2023-01-31 18:21:59.495 DEBUG (MainThread) [custom_components.ytube_music_player.sensor] updating ytube sensor
2023-01-31 18:21:59.496 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_extra_sensor [E]
2023-01-31 18:21:59.496 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] _tracks_to_attribute
2023-01-31 18:21:59.540 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] play_media, media_type: playlist, media_id: RL36w98SNnACPF2PeSg6U6ZL0Vn3_Iu
2023-01-31 18:21:59.540 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_prepare_play
2023-01-31 18:21:59.541 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2023-01-31 18:21:59.541 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current media_player.pantalla_google)  [E]
2023-01-31 18:22:00.074 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher
2023-01-31 18:22:00.074 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.pantalla_google: idle -> idle ... not playing [E]
2023-01-31 18:22:00.416 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_cipher
2023-01-31 18:22:00.417 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_prepare_play
2023-01-31 18:22:00.487 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] get_playlist(playlistId=RL36w98SNnACPF2PeSg6U6ZL0Vn3_Iu)
2023-01-31 18:22:00.487 ERROR (MainThread) [custom_components.ytube_music_player.media_player]

 == == == == == == = ytube_music_player Integration Error == == == == == == == ==
2023-01-31 18:22:00.488 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2023-01-31 18:22:00.489 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2023-01-31 18:22:00.490 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2023-01-31 18:22:00.491 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in async_play_media
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in <lambda>
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/playlists.py", line 104, in get_playlist
    response = self._send_request(endpoint, body)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/ytmusic.py", line 144, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 404: Not Found.
Requested entity was not found.

2023-01-31 18:22:00.492 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2023-01-31 18:22:00.493 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == ==


2023-01-31 18:22:00.494 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_turn_off_media_player [E]
```

Thank you very much in advance for your help

**Comment by slabbel** [comment] 2023-02-02 11:38
Same issue here...

**Comment by AleksandrBraun** [comment] 2023-02-20 08:33
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1558
Integration: YouTube Music Player (documentation, issues)
First occurred: 09:54:59 (7 occurrences)
Last logged: 09:54:59

https://github.com/KoljaWindeler/ytube_music_player/issues
and paste the following output:
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1506, in async_play_media self._tracks = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit)) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/ytube_music_player/media_player.py", line 1506, in <lambda> self._tracks = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit)) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/playlists.py", line 104, in get_playlist response = self._send_request(endpoint, body) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/ytmusic.py", line 134, in _send_request response = self._session.post(YTM_BASE_API + endpoint + YTM_PARAMS + additionalParams, File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post return self.request("POST", url, data=data, json=json, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request conn.request(method, url, **httplib_request_kw) File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "/usr/local/lib/python3.10/http/client.py", line 1282, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/local/lib/python3.10/http/client.py", line 1323, in _send_request self.putheader(hdr, value) File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 224, in putheader _HTTPConnection.putheader(self, header, *values) File "/usr/local/lib/python3.10/http/client.py", line 1247, in putheader header = header.encode('ascii') UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-11: ordinal not in range(128)
thanks, Kolja
== == == == == == = ytube_music_player Integration Error == == == == == == == ==

**Comment by jurgenweber** [comment] 2023-02-27 05:50
I find if I go into the 'media_player' and then hit 'library playlists' I get the following error:

```
2023-02-27 16:48:02.230 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139724087406560] Error handling message: Unknown error (unknown_error) from 124.168.160.63 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1226, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1977, in async_browse_media
    response = await build_item_response(self, payload)
  File "/config/custom_components/ytube_music_player/browse_media.py", line 67, in build_item_response
    media = await hass.async_add_executor_job(media_library.get_library_playlists, BROWSER_LIMIT)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 31, in get_library_playlists
    results = nav(results, ITEM_SECTION + GRID)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav
    raise err
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav
    root = root[k]
TypeError: 'NoneType' object is not subscriptable
```

I must of worked once, since I have the ID's of some of my playlists. :)

**Comment by jurgenweber** [comment] 2023-03-07 21:37
I think these two are these dupes: https://github.com/KoljaWindeler/ytube_music_player/issues/227

So the issue is not this component but a library it uses.

https://github.com/sigma67/ytmusicapi

I found this issue; https://github.com/sigma67/ytmusicapi/issues/320

it seems all loosely related.

the fix is in the latest version; https://github.com/sigma67/ytmusicapi/releases/tag/0.25.0

but main is on 0.24.0

https://github.com/KoljaWindeler/ytube_music_player/blob/12c8c0e9811dd5996f0df3eb2b1cf63a2619f2c7/custom_components/ytube_music_player/manifest.json

I forked; https://github.com/jurgenweber/ytube_music_player. I will try it on miner and see how we go

**Comment by jurgenweber** [comment] 2023-03-07 21:51
oddly, when I check it out on the disk on my HASS machine, I found the version of 0.19.5, thats odd.

I then checked the integration, I don't have all of the versions found in this repos tags:

https://github.com/KoljaWindeler/ytube_music_player/tags

![image](https://user-images.githubusercontent.com/3013734/223560079-fe8cadbf-f2e4-4599-841c-a8bb10028acc.png)

So, I got it to download 'main' in that photo and I got 0.24.0.

After restarting HASS it then worked, so there you go. Do not need my branch/PR after all.

**Comment by rillekille** [comment] 2023-03-09 05:05
https://github.com/KoljaWindeler/ytube_music_player/issues/228#issuecomment-1458922568

This solved my problem too.
Thanks a lot! :-)

**Comment by jsermer** [comment] 2023-04-03 23:10
odd, I experienced the same issue of having a pretty old version on disk:

previous:
```
ytube_music_player # cat manifest.json
{
  "domain": "ytube_music_player",
  "name": "YouTube Music Player",
  "documentation": "https://github.com/KoljaWindeler/ytube_music_player",
  "config_flow": true,
  "issue_tracker": "https://github.com/KoljaWindeler/ytube_music_player/issues",
  "requirements": [
    "ytmusicapi==0.19.5",
    "pytube==10.5.1",
    "integrationhelper==0.2.2"
  ],
  "dependencies": [
    "persistent_notification"
  ],
  "codeowners": [
    "@KoljaWindeler"
  ],
  "iot_class": "cloud_polling",
  "version": "20220205.01"
}
```

current (after going into hacs and forcing a redownload):
```
ytube_music_player # cat manifest.json
{
  "domain": "ytube_music_player",
  "name": "YouTube Music Player",
  "documentation": "https://github.com/KoljaWindeler/ytube_music_player",
  "config_flow": true,
  "issue_tracker": "https://github.com/KoljaWindeler/ytube_music_player/issues",
  "requirements": [
    "ytmusicapi==0.25.0",
    "pytube==10.5.1",
    "integrationhelper==0.2.2"
  ],
  "dependencies": [
    "persistent_notification"
  ],
  "codeowners": [
    "@KoljaWindeler"
  ],
  "iot_class": "cloud_polling",
  "version": "20230321.01"
}
```

Now everything works as expected.  I initially thought I was experiencing the same issue as: https://github.com/KoljaWindeler/ytube_music_player/issues/223

**Closed** 2024-01-13 18:20 UTC
