### ISSUE TITLE
Cannot find the repo in HACS

### ISSUE THREAD

**Issue by ragaimeena** [KoljaWindeler/ytube_music_player#24] opened 2020-12-18 13:26 UTC
as above trying to install via HACS, but cannot find it. when I search nothing comes back. I am new to HA. Thanks in advance

**Comment by KoljaWindeler** [comment] 2020-12-18 13:46
Waiting for https://github.com/home-assistant/wheels-custom-integrations/pull/190

In the meantime add it as custom repository

**Comment by ragaimeena** [comment] 2021-03-19 21:32
the playlist radio option stopped working. Can u advise how to fix it

**Comment by KoljaWindeler** [comment] 2021-03-19 21:55
As always: please turn on debug information (see readme) and try to turn it on. Then copy the debug log into this ticket please

**Comment by ragaimeena** [comment] 2021-03-20 06:59
============= ytube_music_player Integration Error ================
2021-03-20 02:54:32 ERROR (SyncWorker_7) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-03-20 02:54:32 ERROR (SyncWorker_7) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-03-20 02:54:32 ERROR (SyncWorker_7) [custom_components.ytube_music_player.media_player] and paste the following output:
2021-03-20 02:54:32 ERROR (SyncWorker_7) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1110, in play_media
self._tracks = self._api.get_watch_playlist(videoId=r_track['videoId'])['tracks']
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/watch.py", line 80, in get_watch_playlist
tracks = parse_watch_playlist(results['contents'])
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/watch.py", line 29, in parse_watch_playlist
'playlistId': nav(data, NAVIGATION_PLAYLIST_ID),
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 210, in nav
raise err
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 204, in nav
root = root[k]
KeyError: 'playlistId'
2021-03-20 02:54:32 ERROR (SyncWorker_7) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2021-03-20 02:54:32 ERROR (SyncWorker_7) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================
2021-03-20 02:54:33 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-03-20 02:54:34 ERROR (Thread-13) [homeassistant.components.cast.media_player] Failed to cast media https://www.home-assistant.io/images/cast/splash.png. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
2021-03-20 02:54:34 ERROR (SyncWorker_9) [custom_components.ytube_music_player.media_player]
============= ytube_music_player Integration Error ================
2021-03-20 02:54:34 ERROR (SyncWorker_9) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-03-20 02:54:34 ERROR (SyncWorker_9) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-03-20 02:54:34 ERROR (SyncWorker_9) [custom_components.ytube_music_player.media_player] and paste the following output:
2021-03-20 02:54:34 ERROR (SyncWorker_9) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1110, in play_media
self._tracks = self._api.get_watch_playlist(videoId=r_track['videoId'])['tracks']
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/watch.py", line 80, in get_watch_playlist
tracks = parse_watch_playlist(results['contents'])
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/watch.py", line 29, in parse_watch_playlist
'playlistId': nav(data, NAVIGATION_PLAYLIST_ID),
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 210, in nav
raise err
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 204, in nav
root = root[k]
KeyError: 'playlistId'
2021-03-20 02:54:34 ERROR (SyncWorker_9) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2021-03-20 02:54:34 ERROR (SyncWorker_9) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================

**Comment by ragaimeena** [comment] 2021-03-20 06:59
and thank you

**Comment by KoljaWindeler** [comment] 2021-03-20 11:56
@sigma67 can you help out? Any idea what that means?

**Comment by sigma67** [comment] 2021-03-20 14:47
I'd need more details on what calls are performed to ytmusicapi.

**Comment by ragaimeena** [comment] 2021-03-20 15:54
Obviously I am a beginner
I installed the custom component as per instructions. 
I have the dropdown input select for source on a lovelace entities card. It used to work whenever I chose the Playlist radio option and create a playlist automatically based on which playlist is chosen in the playlist dropdown menu. now, and without changing anything, the behaviour of that option is what you see in these logs. so what other info I can provide to help reolve it?
Thanks

**Comment by ragaimeena** [comment] 2021-03-22 14:11
I appreciate if yo can help please thanks

**Comment by sigma67** [comment] 2021-03-22 15:02
I am only able to help if you tell me the video or playlist that is causing this error for you.

**Comment by KoljaWindeler** [comment] 2021-03-22 17:43
Hi, so playing a playlist straight works, but any playlist as radio fails?

**Comment by ragaimeena** [comment] 2021-03-22 18:28
yes exactly. and in the past it used to work. No changes made on my side. Thanks for your help. I enjoy the addon

**Comment by KoljaWindeler** [comment] 2021-03-23 07:55
please update to this version https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20210323
enable debug https://github.com/KoljaWindeler/ytube_music_player#1-reroute-debug-output-to-error-via-service and post your log file again, that should post some info in the fashion of 

`2021-03-23T07:45:46.488392840Z 2021-03-23 08:45:46 ERROR (SyncWorker_33) [custom_components.ytube_music_player.media_player] get_playlist(playlistId=PLZvjm51R8SGuWhMtfSu-A17Kp3jZfg6pg)
`

**Comment by sigma67** [comment] 2021-03-23 11:17
I experimented a bit with radios and `get_watch_playlist`. I found out that you cannot use radio playlists with `get_watch_playlist_shuffle` (kinda makes sense, but probably not related to this). 

The error seems to indicate that there is some entry in the watch playlist that does not have an associated radio playlist for some reason. This should be easily fixable, but I'd like to reproduce it first. For that I'd need the videoId being passed in 

```python
self._api.get_watch_playlist(videoId=r_track['videoId'])['tracks']
```

**Comment by ragaimeena** [comment] 2021-03-23 11:45
2021-03-23 07:44:05 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] TURNON
2021-03-23 07:44:05 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] play_media, media_type: channel, media_id: LM
2021-03-23 07:44:05 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] prepare_play
2021-03-23 07:44:05 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] check_api
2021-03-23 07:44:05 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] - no valid API, try to login
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] - YouTube Api initialized ok, version: 0.14.3
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] _update_remote_player
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] _turn_on_media_player
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] _get_cipher
2021-03-23 07:44:06 ERROR (SyncWorker_15) [custom_components.ytube_music_player.media_player] _sync_player
2021-03-23 07:44:06 ERROR (SyncWorker_15) [custom_components.ytube_music_player.media_player] media_player.shield: off -> idle
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] get_playlist(playlistId=LM) ... get_watch_playlist(videoId=eDB4ULCHCAE)
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player]
============= ytube_music_player Integration Error ================
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] and paste the following output:
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1124, in play_media
self._tracks = self._api.get_watch_playlist(videoId=r_track['videoId'])['tracks']
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/watch.py", line 80, in get_watch_playlist
tracks = parse_watch_playlist(results['contents'])
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/watch.py", line 29, in parse_watch_playlist
'playlistId': nav(data, NAVIGATION_PLAYLIST_ID),
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 210, in nav
raise err
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 204, in nav
root = root[k]
KeyError: 'playlistId'
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] turn_off
2021-03-23 07:44:06 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] _turn_off_media_player
2021-03-23 07:44:06 ERROR (Thread-14) [homeassistant.components.cast.media_player] Failed to cast media https://www.home-assistant.io/images/cast/splash.png. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
2021-03-23 07:44:06 ERROR (SyncWorker_8) [custom_components.ytube_music_player.media_player] _sync_player
2021-03-23 07:44:06 ERROR (SyncWorker_8) [custom_components.ytube_music_player.media_player] media_player.shield: idle -> idle
2021-03-23 07:44:06 ERROR (SyncWorker_20) [custom_components.ytube_music_player.media_player] _sync_player
2021-03-23 07:44:06 ERROR (SyncWorker_20) [custom_components.ytube_music_player.media_player] media_player.shield: idle -> off

**Comment by ragaimeena** [comment] 2021-03-23 11:46
hope this is helpful
thank you

**Comment by sigma67** [comment] 2021-03-23 13:51
I can't reproduce the issue, probably since radios depend on your location as well. 

But I found that the playlistId is the same for each entry, so I'll use a different approach in getting it. Should fix your issue hopefully. You can try again with the latest master of ytmusicapi, I just pushed a fix.

**Comment by ragaimeena** [comment] 2021-03-23 16:16
Kolja
how do I update to the latest version of ytmusicapi via the ytube media player in HASS?

**Comment by sigma67** [comment] 2021-03-24 12:54
I will publish a release this week if nothing else comes up, that should make updating easier.

**Comment by ragaimeena** [comment] 2021-03-24 17:18
Thank you guys,, This was a great feature that I hope will be coming back. I wonder if this is only happening to me or this is a glitch in the API affecting everyone. I really appreciate if it can be fixed. I appreciate your time. Thanks again

**Comment by sigma67** [comment] 2021-03-25 12:34
https://github.com/sigma67/ytmusicapi/releases/tag/0.15.0

**Comment by ragaimeena** [comment] 2021-03-25 12:41
Thank you. My question is to Kolja, how do I implement this new release in his HASS addon? does it automatically pull the new release?
I appreciate your help

**Comment by KoljaWindeler** [comment] 2021-03-25 16:26
Hi, yep, I'm already testing and will update shortly

**Comment by KoljaWindeler** [comment] 2021-03-25 16:41
https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20210325

**Comment by ragaimeena** [comment] 2021-03-25 16:41
thank you. I hope i didnt do anything stupid in the process. let me know if you need me to provide any other data from the logger

**Comment by ragaimeena** [comment] 2021-03-25 16:47
You guys are THE BEST IT WORKED
Is there anyway you can explain what happened in simple terms? I am learning and this is awesome

**Comment by sigma67** [comment] 2021-03-25 17:30
Basically a data entry was missing in one of the videos in your watch playlist. ytmusicapi was expecting it to be there, when it wasn't it crashed. I just changed it to also work when the entry is missing

**Comment by KoljaWindeler** [comment] 2021-03-25 18:13
👍 I'll close this now, thanks @sigma67

**Closed by KoljaWindeler** 2021-03-25 18:13 UTC
