### ISSUE TITLE
Unable to Select Playlists

### ISSUE THREAD

**Issue by WillScott73** [KoljaWindeler/ytube_music_player#215] opened 2022-10-21 08:17 UTC
I can only select my "last Played Songs" playlist. All others generate the error below.

I only installed this integration yesterday and it was working fine, until this morning. I've removed and re-installed it, and have the same issue. Perhaps something changed at Google's end?

```
This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1057
Integration: YouTube Music Player (documentation, issues)
First occurred: 09:08:30 (7 occurrences)
Last logged: 09:08:30

https://github.com/KoljaWindeler/ytube_music_player/issues
and paste the following output:
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in async_update_playlists self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in <lambda> self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 31, in get_library_playlists results = nav(results, ITEM_SECTION + GRID) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav raise err File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav root = root[k] TypeError: 'NoneType' object is not subscriptable
thanks, Kolja
== == == == == == = ytube_music_player Integration Error == == == == == == == ==
```
there is an associated log

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ytube_music_player/browse_media.py:67
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:12:18 (1 occurrences)
Last logged: 09:12:18

[547695887408] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1232, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1977, in async_browse_media
    response = await build_item_response(self, payload)
  File "/config/custom_components/ytube_music_player/browse_media.py", line 67, in build_item_response
    media = await hass.async_add_executor_job(media_library.get_library_playlists, BROWSER_LIMIT)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 31, in get_library_playlists
    results = nav(results, ITEM_SECTION + GRID)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav
    raise err
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav
    root = root[k]
TypeError: 'NoneType' object is not subscriptable


```

**Comment by simonmannsfeld** [comment] 2022-11-04 07:49
@WillScott73 This issue is caused by ytmusicapi and only fixable with updating the version of ytmusicapi within the dependencies. I did it in PR #217. Waiting for merge.

**Comment by WillScott73** [comment] 2022-11-04 09:38
Thanks

**Comment by simonmannsfeld** [comment] 2022-11-04 15:39
@KoljaWindeler please mark this issue as resolved.

**Comment by KHV8** [comment] 2022-11-12 14:32
Is it only me, or have this stopped working again on upgrade to 2022.11.2. Im sure my automations worked earlier in the week, however have stopped from friday. This fit a upgrade to 2022.11.2 I did Thursday.
Im on latest HACS version of ytube, called 20221106

**Comment by simonmannsfeld** [comment] 2022-11-12 16:34
@KHV8 Are there some errors in log? My integration is working fine.

**Comment by KHV8** [comment] 2022-11-14 20:30
@simonmannsfeld 

Have looked further into it. Think something has happend to my cookie text. Maybe it have expiered or alike.

I get these 2 errors when I try and play a "playlist" which I know was working last week. It has been working for at least 1 year, and I know it was operational every day, as it plays music in our bath when light turns on:-)
Have tried to create a new ytube media player, this one generates the same error in the logs.

I know it activates the Google Home, as the initial "activate beep" is happening on the device.

I have tested with the URL from the second error message in a normal crome browser, and it returns get a access denided information.

Unless you got some idea, then I will try and create a cookie text next weekend. Remember it took some time.


************************************
First error message
************************************
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1586
Integration: yTubeMediaPlayer ([documentation](https://github.com/KoljaWindeler/ytube_music_player), [issues](https://github.com/KoljaWindeler/ytube_music_player/issues))
First occurred: 21:08:52 (3 occurrences)
Last logged: 21:08:52

- Failed to get own(!) URL for track, further details below. Will not try YouTube method
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1421, in async_get_url self._signatureTimestamp = await self.hass.async_add_executor_job(self._api.get_signatureTimestamp) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/browsing.py", line 718, in get_signatureTimestamp url = self.get_basejs_url() File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/browsing.py", line 704, in get_basejs_url raise Exception("Could not identify the URL for base.js player.") Exception: Could not identify the URL for base.js player.
Wv986XabsdQ


************************************
Second error message
************************************

Logger: homeassistant.components.cast.media_player
Source: components/cast/media_player.py:398
Integration: Google Cast ([documentation](https://www.home-assistant.io/integrations/cast), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+cast%22))
First occurred: 21:08:52 (1 occurrences)
Last logged: 21:08:52

Failed to cast media https://rr8---sn-uqj-j2id.googlevideo.com/videoplayback?expire=1668478131&ei=U6ByY-XyKbGTv_IP65ahuAQ&ip=194.239.204.178&id=o-AEIWreNYR8zYfi0FFHNoUKTIplc4KWTYwEAfLi2za8ke&itag=140&source=youtube&requiressl=yes&mh=-Q&mm=31%2C29&mn=sn-uqj-j2id%2Csn-5go7yne6&ms=au%2Crdu&mv=m&mvi=8&pl=22&initcwndbps=2148750&spc=SFxXNpHpS4jGi6JanqBHk-92ghvr9TQ&vprv=1&mime=audio%2Fmp4&ns=I-x4YKRP9StuZWvZTuL4sIsJ&gir=yes&clen=90933146&dur=5725.343&lmt=1488530195095021&mt=1668456117&fvip=2&keepalive=yes&fexp=24001373%2C24007246&beids=24239133&c=WEB_REMIX&n=dsxPf05hwy_A4RBi&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAJLzubOr4vbN51qZMnROyzadrootoBNWfTUEgtkR1OeEAiB4uXKusZ-Ucbyc01aB2D63H2OQ23JzD5Q1o-oaphYbUw%3D%3D&sig=kNwg-_XwrBI_ML7019xdMPQnvrQR5bJGrWGlXXkv93AEiAsXn5oWsnQYq=j1X-WUS98QFpRbf8RJQVXkpry4ixYAJAhIgRw8JQ0qOAkOA4. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

**Comment by simonmannsfeld** [comment] 2022-11-14 23:24
@KHV8 it seems to be an completely different error. I guess you have to pick a fresh cookie. Please try this with config flow. If the error still occurs, feel free to open an own GitHub issue for that error.

@KoljaWindeler Please close this issue. 😎

**Closed** 2022-11-15 11:27 UTC
Labels: bug
