### ISSUE TITLE
Playlist with training space cannot be played

### ISSUE THREAD

**Issue by 29w211barnes** [KoljaWindeler/ytube_music_player#25] opened 2020-12-21 05:38 UTC
I discovered that one of my playlists would not work.  Took me a bit to discover that the playlist name had a trailing space.  "Christmas "  instead of "Christmas".   While it would show in the input select, you could not choose it.  
I was able to work around the problem by removing the space in the playlist name, but you might want to account for this possible issue in code.

**Comment by simonmannsfeld** [comment] 2020-12-24 13:57
@29w211barnes I cannot reproduce your error. It seems that it's not possible to save a playlist with trailing space at Youtube Music. How did you create a playlist with trailing space on playlist name?

**Comment by KoljaWindeler** [comment] 2020-12-26 11:55
same here .. I can't create such a playlist .. I'll close this here. Please reopen if you find a way to create a playlist with trailing space

**Closed by KoljaWindeler** 2020-12-26 11:55 UTC

**Comment by 29w211barnes** [comment] 2020-12-26 22:50
Curious.  It was a playlist that was transferred over from google music, so
perhaps it was an issue in the transfer process that created the extra
space?
