### ISSUE TITLE
Device Cards under playback devices overlap

### ISSUE THREAD

**Issue by happyhammer7** [KoljaWindeler/ytube_music_player#194] opened 2022-06-01 09:44 UTC
**Describe the bug**
When selecting the option "playback device" to change speakers, the cards that are displayed for each individual speaker overlap the cards above them so you cannot see the names of the speakers. This happens when you select more than 2 or 3 speakers depending on the size of the device you are using (ie mobile is 2, desktop is 3) as this is when the cards more down vertically

**Version**
1.25.5

**To Reproduce**
1. Go to 'youtube_music_player'
2. Click on 'browse media'
3. Scroll down to 'playback device"

![image](https://user-images.githubusercontent.com/35979039/171376098-26aa92af-74aa-435b-b904-15a3d4d08ec5.png)

Thanks

**Comment by Wihanh** [comment] 2022-06-07 10:20
+1

**Comment by tiaanv** [comment] 2022-06-14 10:41
+1

**Comment by KoljaWindeler** [comment] 2022-07-22 05:27
Sorry guys, can't reproduce it.
And even if: that can only be fixed in Homeassistant.
I'm only passing the name and no design related information
Kolja

**Closed** 2024-01-13 18:26 UTC
Labels: bug
