### ISSUE TITLE
Attempting to play anything just skips through track names but doesn't play anything

### ISSUE THREAD

**Issue by wildoracle** [KoljaWindeler/ytube_music_player#301] opened 2024-01-25 01:21 UTC
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
A clear and concise description of what the bug is, ideally a homeassistant log with debug enabled
Playing from YTube Music in the media browser causes my google speaker group to make a sound as though playback will begin, but nothing plays and the playback area just flips between album art and track names every few seconds without playing anything.

I'm not sure how to properly copy and paste the logs here...

STOP command requested but no session is active.
5:14:15 PM – (WARNING) components/cast/media_player.py - message first occurred at 5:04:50 PM and shows up 6 times
- decoded url return 403 status code
5:14:15 PM – (ERROR) yTubeMediaPlayer (custom integration) - message first occurred at 5:13:20 PM and shows up 69 times
[S] async_sync_player ... media_player.speakers: idle -> idle ... not playing [E]
5:14:15 PM – (ERROR) yTubeMediaPlayer (custom integration) - message first occurred at 5:13:37 PM and shows up 23 times
HTTP Error 410: Gone
5:14:15 PM – (ERROR) yTubeMediaPlayer (custom integration) - message first occurred at 5:04:44 PM and shows up 12 times
- Failed to get URL with YouTube methode
5:14:15 PM – (ERROR) yTubeMediaPlayer (custom integration) - message first occurred at 5:04:44 PM and shows up 12 times
- Retry with: (3)
5:14:10 PM – (ERROR) yTubeMediaPlayer (custom integration) - message first occurred at 5:04:44 PM and shows up 9 times

**Version**
please provide the version you are using (see HACS)
20240112.01

**To Reproduce**
1. Go to 'Media' on the sidebar
2. Click on 'YTUBE_MUSIC_PLAYER' bottom right (or it's already selected)
3. Select 'Library Playlists'
4. Play any playlist
5. See error

**Additional context**
I had the beta installed, I uninstalled everything then tried installing the non-beta. Same error.
Thanks

**Comment by h4de5** [comment] 2024-01-25 03:38
same issue here.

**Comment by KoljaWindeler** [comment] 2024-01-25 05:15
Hi, that's not good ;)
Is this happening for every album / playlist?
Did it work before or is this the first time you test the integration? 

The "gone" issue appears every once in awhile from Ytube and disappears a day later. It still works here as of now

**Comment by Thorsten1982** [comment] 2024-01-25 07:11
So it worked for me before and now I have the same problems. I noticed if I only want to play one song it seems to work, only if there are several titles, e.g. an album or playlist it doesn't work

**Comment by Thorsten1982** [comment] 2024-01-25 07:14
[home-assistant_ytube_music_player_2024-01-25T07-13-37.451Z.log](https://github.com/KoljaWindeler/ytube_music_player/files/14047978/home-assistant_ytube_music_player_2024-01-25T07-13-37.451Z.log)

**Comment by KoljaWindeler** [comment] 2024-01-25 07:20
Interesting. Could one of you bump the dependency version of pytube to 15.0.0 (in the manifest.json) as shown here https://github.com/KoljaWindeler/ytube_music_player/blob/main/custom_components/ytube_music_player/manifest.json
I'm running this on my setup with the gone issue and it was mentioned in the other ticket as a possible solution

**Comment by Thorsten1982** [comment] 2024-01-25 07:35
I don't know if I did it right, I opened the manifest.json file in the file editor and changed one line so that it says 15.0.0. I restarted Home Assistant and still the same error

**Comment by KoljaWindeler** [comment] 2024-01-25 08:47
Jep, that is the correct procedure.
Too bad that it didn't fix the issue that easily.. 

Well I'll look into it, but I guess this is not a quick fix, as it is caused by ytubes server and it works most of the time.

**Comment by Thorsten1982** [comment] 2024-01-25 09:20
Oh, okay.  I've been using the plugin for about a year and have never had this problem.  I noticed it for the first time yesterday and it hasn't worked since then.

**Comment by KoljaWindeler** [comment] 2024-01-25 10:31
Nope, Not new

https://github.com/KoljaWindeler/ytube_music_player/issues/238

**Comment by Thorsten1982** [comment] 2024-01-25 10:59
I don't know if it's relevant but I also noticed that after many attempts the song ended up playing. So I press play song and then it tries to play the song again and again and then at some point the song starts playing. Sometimes it takes 5 attempts, sometimes more

**Comment by wildoracle** [comment] 2024-01-25 16:27
> Hi, that's not good ;) Is this happening for every album / playlist? Did it work before or is this the first time you test the integration?
> 
> The "gone" issue appears every once in awhile from Ytube and disappears a day later. It still works here as of now

I've been using this integration for a few years now, this issue has happened before, but not recently. Your updates from a few months ago that fixed the login issues (when I used to have to submit that cookie nearly daily🍪😂) took care of this as well.

**Comment by KoljaWindeler** [comment] 2024-01-25 20:58
Great, usually the "gone" disappears without doing anything but it is still a problem. I'll close this ticket and keep track in the other linked ticket

**Closed by KoljaWindeler** 2024-01-25 20:58 UTC
Labels: bug

**Comment by wildoracle** [comment] 2024-01-29 20:37
Dang, @KoljaWindeler your latest update I installed this morning brought this bug back for me.
